//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaceAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2021_vApex_Flag_Logo4_RG_Black {
            get {
                object obj = ResourceManager.GetObject("2021 vApex Flag Logo4-RG-Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string ColorName_Control {
            get {
                return ResourceManager.GetString("ColorName_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string ColorName_Gold {
            get {
                return ResourceManager.GetString("ColorName_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndianRed.
        /// </summary>
        internal static string ColorName_IndianRed {
            get {
                return ResourceManager.GetString("ColorName_IndianRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid number was not entered..
        /// </summary>
        internal static string ErrorMessage_ValidNumberNotEntered {
            get {
                return ResourceManager.GetString("ErrorMessage_ValidNumberNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarNum.
        /// </summary>
        internal static string TableColumn_CarNum {
            get {
                return ResourceManager.GetString("TableColumn_CarNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverLapNum.
        /// </summary>
        internal static string TableColumn_DriverLapNum {
            get {
                return ResourceManager.GetString("TableColumn_DriverLapNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverName.
        /// </summary>
        internal static string TableColumn_DriverName {
            get {
                return ResourceManager.GetString("TableColumn_DriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident.
        /// </summary>
        internal static string TableColumn_Incident {
            get {
                return ResourceManager.GetString("TableColumn_Incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string TableColumn_Team {
            get {
                return ResourceManager.GetString("TableColumn_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string TableColumn_Time {
            get {
                return ResourceManager.GetString("TableColumn_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TableColumn_Total {
            get {
                return ResourceManager.GetString("TableColumn_Total", resourceCulture);
            }
        }
    }
}
