//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaceAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2021_vApex_Flag_Logo4_RG_Black {
            get {
                object obj = ResourceManager.GetObject("2021 vApex Flag Logo4-RG-Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorPickerIcon {
            get {
                object obj = ResourceManager.GetObject("ColorPickerIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConeEmpty {
            get {
                object obj = ResourceManager.GetObject("ConeEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConeFull {
            get {
                object obj = ResourceManager.GetObject("ConeFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carBetweenPitCones.
        /// </summary>
        internal static string DebugTable_CarBetweenPitCones {
            get {
                return ResourceManager.GetString("DebugTable_CarBetweenPitCones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carClassPosition.
        /// </summary>
        internal static string DebugTable_CarClassPosition {
            get {
                return ResourceManager.GetString("DebugTable_CarClassPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carClassShortName.
        /// </summary>
        internal static string DebugTable_CarClassShortName {
            get {
                return ResourceManager.GetString("DebugTable_CarClassShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carCurrentLap.
        /// </summary>
        internal static string DebugTable_CarCurrentLap {
            get {
                return ResourceManager.GetString("DebugTable_CarCurrentLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carIdx.
        /// </summary>
        internal static string DebugTable_CarIdx {
            get {
                return ResourceManager.GetString("DebugTable_CarIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carLapsCompleted.
        /// </summary>
        internal static string DebugTable_CarLapsCompleted {
            get {
                return ResourceManager.GetString("DebugTable_CarLapsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carNumber.
        /// </summary>
        internal static string DebugTable_CarNumber {
            get {
                return ResourceManager.GetString("DebugTable_CarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carOverallPosition.
        /// </summary>
        internal static string DebugTable_CarOverallPosition {
            get {
                return ResourceManager.GetString("DebugTable_CarOverallPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carPercentAroundTrack.
        /// </summary>
        internal static string DebugTable_CarPercentAroundTrack {
            get {
                return ResourceManager.GetString("DebugTable_CarPercentAroundTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carTrackSurface.
        /// </summary>
        internal static string DebugTable_CarTrackSurface {
            get {
                return ResourceManager.GetString("DebugTable_CarTrackSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carTrackSurfaceMatrerial.
        /// </summary>
        internal static string DebugTable_CarTrackSurfaceMaterial {
            get {
                return ResourceManager.GetString("DebugTable_CarTrackSurfaceMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to driverName.
        /// </summary>
        internal static string DebugTable_DriverName {
            get {
                return ResourceManager.GetString("DebugTable_DriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid number was not entered..
        /// </summary>
        internal static string ErrorMessage_ValidNumberNotEntered {
            get {
                return ResourceManager.GetString("ErrorMessage_ValidNumberNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carClass.
        /// </summary>
        internal static string IncidentsTable_CarClass {
            get {
                return ResourceManager.GetString("IncidentsTable_CarClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carNumber.
        /// </summary>
        internal static string IncidentsTable_CarNumber {
            get {
                return ResourceManager.GetString("IncidentsTable_CarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to driverLapNumber.
        /// </summary>
        internal static string IncidentsTable_DriverLapNumber {
            get {
                return ResourceManager.GetString("IncidentsTable_DriverLapNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to driverName.
        /// </summary>
        internal static string IncidentsTable_DriverName {
            get {
                return ResourceManager.GetString("IncidentsTable_DriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hiddenTimeStamp.
        /// </summary>
        internal static string IncidentsTable_HiddenTimeStamp {
            get {
                return ResourceManager.GetString("IncidentsTable_HiddenTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incidentValue.
        /// </summary>
        internal static string IncidentsTable_IncidentValue {
            get {
                return ResourceManager.GetString("IncidentsTable_IncidentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localTime.
        /// </summary>
        internal static string IncidentsTable_LocalTime {
            get {
                return ResourceManager.GetString("IncidentsTable_LocalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sessionTime.
        /// </summary>
        internal static string IncidentsTable_SessionTime {
            get {
                return ResourceManager.GetString("IncidentsTable_SessionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teamName.
        /// </summary>
        internal static string IncidentsTable_TeamName {
            get {
                return ResourceManager.GetString("IncidentsTable_TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to totalIncidents.
        /// </summary>
        internal static string IncidentsTable_TotalIncidents {
            get {
                return ResourceManager.GetString("IncidentsTable_TotalIncidents", resourceCulture);
            }
        }
    }
}
